export const EventType = Object.freeze({
  KEY_DOWN: "keydown",
  KEY_UP: "keyup",
  POINTER_DOWN: "pointerdown",
  POINTER_UP: "pointerup",
  POINTER_MOVE: "pointermove",
  WHEEL: "wheel",
  GESTURE: "gesture",
  TEXT_INPUT: "textinput",
  COMPOSITION_START: "compositionstart",
  COMPOSITION_UPDATE: "compositionupdate",
  COMPOSITION_END: "compositionend",
  GAMEPAD_CONNECTED: "gamepadconnected",
  GAMEPAD_DISCONNECTED: "gamepaddisconnected",
  GAMEPAD_BUTTON_DOWN: "gamepadbuttondown",
  GAMEPAD_BUTTON_UP: "gamepadbuttonup",
});
